#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import re

ROOT = Path('.')
IGNORE_DIR_PREFIXES = ('.git', '.godot', '.patch', '.local_project_backups', '.patch_backups')
CONTROL_TYPES = ('Control', 'Button', 'Label', 'RichTextLabel', 'Panel', 'PanelContainer', 'ColorRect', 'HBoxContainer', 'VBoxContainer', 'GridContainer', 'ScrollContainer', 'TextureRect')
ALLOWED_COMPONENT_SCRIPTS = {
    'scripts/ui/panels/UIPanelBase.gd',
    'scripts/ui/panels/CraftingItemDragButton.gd',
    'scripts/ui/components/PassiveTreeNodeButton.gd',
    'scripts/ui/components/PassiveTreeConnectionCanvas.gd',
}
ALLOWED_DATA_DRIVEN_GENERATION = {
    'scripts/ui/panels/PassiveAtlasPanel.gd',
    'scripts/ui/panels/CraftingPanel.gd',
}
FORBIDDEN_GAME_ROOT_SCENES = (
    'res://scenes/ui/panels/LootFilterPanel.tscn',
    'res://scenes/ui/hud/FlaskHUD.tscn',
)

def skip(path: Path) -> bool:
    return any(part.startswith(IGNORE_DIR_PREFIXES) for part in path.parts)

def project_files(pattern: str):
    for p in ROOT.glob(pattern):
        if not skip(p):
            yield p

def scene_references(path_text: str) -> bool:
    for tscn in project_files('**/*.tscn'):
        try:
            if path_text in tscn.read_text():
                return True
        except UnicodeDecodeError:
            continue
    return False

def main() -> int:
    errors = []
    warnings = []
    game_root = ROOT / 'scripts/core/GameRoot.gd'
    if game_root.exists():
        text = game_root.read_text()
        for scene_path in FORBIDDEN_GAME_ROOT_SCENES:
            if scene_path in text:
                errors.append(f'{game_root} — GameRoot directly loads UI scene {scene_path}; UI must be owned by GameHUD/UIPanelRoot scenes.')
    hud_scene = ROOT / 'scenes/ui/GameHUD.tscn'
    if (ROOT / 'scenes/ui/hud/FlaskHUD.tscn').exists() and (not hud_scene.exists() or 'res://scenes/ui/hud/FlaskHUD.tscn' not in hud_scene.read_text()):
        errors.append('scenes/ui/GameHUD.tscn — FlaskHUD.tscn exists but is not scene-owned by GameHUD.tscn.')
    panel_root_scene = ROOT / 'scenes/ui/UIPanelRoot.tscn'
    if (ROOT / 'scenes/ui/panels/LootFilterPanel.tscn').exists() and (not panel_root_scene.exists() or 'res://scenes/ui/panels/LootFilterPanel.tscn' not in panel_root_scene.read_text()):
        errors.append('scenes/ui/UIPanelRoot.tscn — LootFilterPanel.tscn exists but is not scene-owned by UIPanelRoot.tscn.')
    for script in project_files('scripts/ui/**/*.gd'):
        rel = script.as_posix()
        text = script.read_text()
        if ('extends Control' in text or 'extends Button' in text or 'extends PanelContainer' in text) and rel not in ALLOWED_COMPONENT_SCRIPTS:
            if not scene_references(rel.replace('scripts/', 'res://scripts/')):
                warnings.append(f'{rel} — Control-derived script is not directly referenced by a .tscn scene; verify it is intentionally loaded/preloaded.')
        if rel in ALLOWED_COMPONENT_SCRIPTS:
            continue
        cleaned = re.sub(r'set_drag_preview\([^\n]+\)', '', text)
        for i, line in enumerate(cleaned.splitlines(), start=1):
            if any(f'{typ}.new()' in line for typ in CONTROL_TYPES):
                level = 'Data-driven UI component creation; allowed only inside scene-owned containers.' if rel in ALLOWED_DATA_DRIVEN_GENERATION else 'Script creates UI node; verify it is not persistent panel layout.'
                warnings.append(f'{rel}:{i} — {level}')
            if '.add_child(' in line and rel not in ALLOWED_DATA_DRIVEN_GENERATION:
                warnings.append(f'{rel}:{i} — UI script calls add_child(); verify it is not building persistent layout.')
    report = ['# Relic Forge: Vaultbound — Scene Authorship Status', '', 'Generated by Patch 085L scene-authorship cleanup.', '', '## Summary', '', f'- Errors: **{len(errors)}**', f'- Warnings: **{len(warnings)}**', '', '## Findings', '']
    if not errors and not warnings:
        report.append('- No scene-authorship issues detected.')
    else:
        for e in errors:
            report.append(f'- **ERROR** `{e}`')
        for w in warnings:
            report.append(f'- **WARNING** `{w}`')
    report += ['', '## Notes', '', '- GameRoot must not directly instantiate UI panel/HUD scenes.', '- GameHUD owns FlaskHUD.', '- UIPanelRoot owns panel scenes such as LootFilterPanel.', '- Data-driven node/item buttons are allowed only inside scene-owned containers.', '- Backup folders are ignored.']
    out = ROOT / 'docs/SCENE_AUTHORSHIP_STATUS.md'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(report) + '\n')
    print(out.read_text())
    return 1 if errors else 0

if __name__ == '__main__':
    raise SystemExit(main())
